# Generated by Django 4.2 on 2023-04-21 17:27

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=40)),
                ('capacity', models.IntegerField()),
                ('number', models.CharField(max_length=10)),
                ('mark', models.CharField(max_length=40)),
                ('rate', models.CharField(choices=[('economy', 'economy'), ('comfort', 'comfort'), ('business', 'business')], max_length=8)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(default='00000000000000', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(default='00000000000000', max_length=15)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxi_manager.car')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('departure', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('arrival', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('rate', models.CharField(choices=[('economy', 'economy'), ('comfort', 'comfort'), ('business', 'business')], max_length=8)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_manager.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_manager.driver')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='CarOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_manager.car')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_manager.order')),
            ],
            options={
                'db_table': 'car_order',
            },
        ),
    ]
