# Generated by Django 4.2 on 2023-04-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('active', 'active'), ('canceled', 'canceled')], default='active', max_length=9),
            preserve_default=False,
        ),
    ]
