# Generated by Django 4.2 on 2023-04-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0003_alter_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_manager.car'),
        ),
    ]
