# Generated by Django 4.2 on 2023-04-30 10:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0004_alter_driver_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='00000000000000', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='00000000000000', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 4, 30, 10, 16, 23, 787888, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
