# Generated by Django 4.2 on 2023-05-01 13:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0005_alter_customer_phone_alter_driver_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rate',
            field=models.CharField(choices=[('economy', 'economy'), ('comfort', 'comfort'), ('business', 'business'), ('executed', 'executed')], max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 1, 13, 31, 19, 480258, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate',
            field=models.CharField(choices=[('economy', 'economy'), ('comfort', 'comfort'), ('business', 'business'), ('executed', 'executed')], max_length=8),
        ),
    ]
