# Generated by Django 4.2 on 2023-05-01 20:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0006_alter_car_rate_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 1, 20, 47, 29, 572817, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate',
            field=models.CharField(choices=[('economy', 'economy'), ('comfort', 'comfort'), ('business', 'business'), ('executed', 'executed')], max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('active', 'active'), ('canceled', 'canceled')], max_length=10),
        ),
    ]
