# Generated by Django 4.2 on 2023-05-03 06:45

import datetime
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0008_alter_order_order_date_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='+0000000000000', max_length=17),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='+0000000000000', max_length=17),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 3, 6, 45, 26, 884708, tzinfo=datetime.timezone.utc))]),
        ),
    ]
