# Generated by Django 4.2 on 2023-05-03 07:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0009_driver_location_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 3, 7, 53, 44, 292150, tzinfo=datetime.timezone.utc))]),
        ),
    ]
