# Generated by Django 4.2 on 2023-05-08 13:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0010_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 8, 13, 40, 11, 21894, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('active', 'active'), ('canceled', 'canceled'), ('executed', 'executed'), ('evaluation', 'evaluation')], max_length=10),
        ),
    ]
