# Generated by Django 4.2 on 2023-05-08 18:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0013_alter_car_rate_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rate',
            field=models.CharField(choices=[('1', 'economy'), ('2', 'comfort'), ('3', 'business')], max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 8, 18, 1, 45, 10421, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate',
            field=models.CharField(choices=[('1', 'economy'), ('2', 'comfort'), ('3', 'business')], max_length=9),
        ),
    ]
