# Generated by Django 4.2 on 2023-05-08 18:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0014_alter_car_rate_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 8, 18, 33, 56, 674588, tzinfo=datetime.timezone.utc))]),
        ),
    ]
