# Generated by Django 4.2 on 2023-05-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0016_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
