# Generated by Django 4.2 on 2023-06-05 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi_manager', '0017_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='+0000000000000', max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='+0000000000000', max_length=30),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account', models.UUIDField(blank=True)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Waiting', 'Waiting')], default='Waiting', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
    ]
