# Generated by Django 4.2 on 2023-06-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_manager', '0018_alter_car_manufacturer_alter_car_mark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
