name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/flake_requirements.txt
    - name: Flake8
      run: flake8 ./taxi
  container-job:
    name: Тесты
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
            POSTGRES_PASSWORD: test
            POSTGRES_DBNAME: postgres
            POSTGRES_USER: test
            POSTGRES_PORT: 5432
            POSTGRES_HOST: 127.0.0.1
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r taxi/requirements.txt
    - name: Тесты django models
      run: |
        ./manage.py test tests.test_models
    - name: Тесты django views
      run: |
        ./manage tests.test_views
    - name: Тесты django rest api
      run: |
        ./manage.py test tests.test_rest
    - name: Тесты django forms
      run: |
        ./manage.py test tests.test_forms