name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/flake_requirements.txt
    - name: Flake8
      run: flake8 .
  container-job:
    name: Тесты
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
            POSTGRES_PASSWORD: test
            POSTGRES_DBNAME: postgres
            POSTGRES_USER: test
            POSTGRES_PORT: 5432
        ports:
          - 5432:5432
    steps:
    - name: Установка GDAL
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
    - name: Set up PostGIS
      run: |
        sudo apt-get -y update
        sudo apt-get -y install postgis
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.6"
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r taxi/requirements.txt
        echo $'POSTGRES_PORT=5432\nPOSTGRES_USER=test\nPOSTGRES_PASSWORD=test\nPOSTGRES_DB=postgres\nPOSTGRES_HOST=postgres' >> taxi/.env
    - name: Тесты django views
      run: |
        python3 taxi/manage.py test tests.test_views
    - name: Тесты django rest api
      run: |
        python3 taxi/manage.py test tests.test_rest
    - name: Тесты django forms
      run: |
        python3 taxi/manage.py test tests.test_forms