name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/flake_requirements.txt
    - name: Flake8
      run: flake8 .
  container-job:
    name: Тесты
    runs-on: ubuntu-latest
    steps:
    - name: Установка GDAL
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
    - name: Set up PostGIS
      run: |
        sudo apt-get -y update
        sudo apt-get -y install postgis
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.6"
    - name: Запуск postgis контейнера
      run: |
        docker run -d --name taxi -p 5999:5432 \
            -v $HOME/postgresql/taxi/:/var/lib/postgresql/taxi \
            -e POSTGRES_PASSWORD=test \
            -e POSTGRES_USER=test \
            -e POSTGRES_DB=test \
            postgis/postgis
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r taxi/requirements.txt
        echo "POSTGRES_PORT=5999" >> taxi/.env
        echo "POSTGRES_USER=test" >> taxi/.env
        echo "POSTGRES_PASSWORD=test" >> taxi/.env
        echo "POSTGRES_DB=test" >> taxi/.env
        echo "POSTGRES_HOST=127.0.0.1" >> taxi/.env
    - name: Тесты django views
      run: |
        python3 taxi/manage.py test tests.test_views
    - name: Тесты django rest api
      run: |
        python3 taxi/manage.py test tests.test_rest
    - name: Тесты django forms
      run: |
        python3 taxi/manage.py test tests.test_forms
